### ISSUE TITLE
Image scaling issues on the About page slides

### ISSUE THREAD

**Issue by mandiwise** [redacademy/spring-spring-2016#6]
This issue was present in Google Chrome:

<img width="1171" alt="about-slider" src="https://cloud.githubusercontent.com/assets/1518780/16314655/c3d5a508-3933-11e6-9979-0bd5713cc878.png">

**Comment by tomroper** [comment]
Rony - I know you were working on this this morning, please push when completed.

**Comment by ronybansal** [comment]
fixed this
