### ISSUE TITLE
RWD issues

### ISSUE THREAD

**Issue by mandiwise** [redacademy/spring-spring-2016#7]
For example, try resizing your content page...some of the content runs off the right side of the screen:

<img width="998" alt="programs-rwd" src="https://cloud.githubusercontent.com/assets/1518780/16314690/f66d6adc-3933-11e6-961f-5d6e375462b6.png">

CSS needs to be re-written so it is fluid between breakpoints.

**Comment by tomroper** [comment]
Jane - were you looking at putting these in a slider or making them responsive?

**Comment by janekim0730** [comment]
@tomroper I put them in the bxslider. I still need to style them though.

**Comment by janekim0730** [comment]
bx slider and styling for single program page is completed
